version: '2.2'

services:
  app:
    image: 'autotests:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    env_file:
      - vars-spring.env
          
  db:
    image: 'postgres:10.18'
    container_name: db
    env_file:
      - vars-postgres.env
